### PR TITLE
added functions for deletion and inorder traversal

### PR DESCRIPTION
**Pull request by ghost**
Added functions for deletion and inorder traversal. Also function declarations were missing in original code. You can implement delete method in your own, similar to insert method, where you can prompt user which node to delete.

### CODE REVIEW

**Review by kambleaa007 — APPROVED** [review]
yes, 
i reviewed it

**Comment by PritKalariya** [comment]
Is there a way where I can merge this to branch named 'Binary Search Tree' ? 
It will help me experiment with it and then I can merge it with the master branch.

**Comment by PritKalariya** [comment]
Try making pull request to the 'Binary Search Tree' branch @sskenjale

**Comment by PritKalariya** [comment]
You can again make a pull request @sskenjale . 
This time I have changed the base branch to the branch i want to merge your PR i.e. 'Binary Search Tree' branch.

**Comment by ghost** [comment]
I think earlier there was no Binary Search Tree branch. right?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by PritKalariya** [comment]
There already existed a branch but the base branch was set to master. Now i have changed it to BST

**Comment by ghost** [comment]
What should I do now? I am still learning GitHub. I don't know much about pull request. This is my first PR😂

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by PritKalariya** [comment]
Don't worry even I'm learning it. I just read about resolving conflicts. Let me see what I can do and I'll get back to you.

**Comment by PritKalariya** [comment]
Recreate a pull request @sskenjale

**Comment by ghost** [comment]
From forked master to your Binary Search Tree Branch?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by PritKalariya** [comment]
Yes!

**Comment by ghost** [comment]
I will DM you what I am getting

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by PritKalariya** [comment]
Ok!

**Pull request closed without merging**
